---
- name: Add authorized key for root
  authorized_key:
    user: root
    state: present
    key: "{{ root_pubkey }}"
  notify: change root password

- name: Create login user
  user:
    name: "{{ login_user }}"
    state: present
    createhome: yes
    shell: /bin/bash
    groups:
      - sudo
      - netdev
      - audio
      - video
      - dialout
      - plugdev
      - input
      - systemd-journal
      - ssh
      - docker

- name: Add authorized key for login user
  authorized_key:
    user: "{{ login_user }}"
    state: present
    key: "{{ login_user_pubkey }}"

- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
