---
- hosts: sensors
  roles:
    - role: nickjj.docker
      tags: docker
      vars:
        docker__apt_repository: >
         deb [arch=armhf]
         https://download.docker.com/linux/{{ ansible_distribution | lower }}
         {{ ansible_distribution_release }} {{ docker__channel | join (' ') }}
    - role: users
      tags: users
    - role: services
      tags: services
